[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_GOOGLE_CLIENT_ID="549406128427-sd68mk83j7kbnr1uvolh1p3en9940p0n.apps.googleusercontent.com"
  ENV="stage"