[build]
  command = "CI='' npm run build"
  publish = "/build"
  base ="/frontend"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_GOOGLE_CLIENT_ID=process.env.REACT_APP_GOOGLE_CLIENT_ID
  ENV=stage